// Day types
export const GET_DAYS = 'GET_DAYS';
export const GET_DAYS_ERROR = 'GET_DAYS_ERROR';
export const GET_DAY = 'GET_DAY';
export const GET_DAY_ERROR = 'GET_DAY_ERROR';

export const UPDATE_DAY_AVAILABILITY_TRUE = 'UPDATE_DAY_AVAILABILITY_TRUE';
export const UPDATE_DAY_AVAILABILITY_TRUE_ERROR =
  'UPDATE_DAY_AVAILABILITY_TRUE_ERROR';
export const UPDATE_DAY_AVAILABILITY_FALSE = 'UPDATE_DAY_AVAILABILITY_FALSE';
export const UPDATE_DAY_AVAILABILITY_FALSE_ERROR =
  'UPDATE_DAY_AVAILABILITY_FALSE_ERROR';
export const DAYS_LOADING = 'DAYS_LOADING';

// Booking types
export const GET_BOOKINGS = 'GET_BOOKINGS';
export const GET_BOOKINGS_ERROR = 'GET_BOOKINGS_ERROR';
export const GET_BOOKING = 'GET_BOOKING';
export const GET_BOOKING_ERROR = 'GET_BOOKING_ERROR';
export const NEW_BOOKING = 'NEW_BOOKING';
export const NEW_BOOKING_ERROR = 'NEW_BOOKING_ERROR';
export const DELETE_BOOKING = 'DELETE_BOOKING';
export const DELETE_BOOKING_ERROR = 'DELETE_BOOKING_ERROR';
export const BOOKINGS_LOADING = 'BOOKINGS_LOADING';
