// Day Actions
export const GET_DAYS = 'GET_DAYS';
export const GET_DAYS_ERROR = 'GET_DAYS_ERROR';
export const GET_DAY = 'GET_DAY';
export const GET_DAY_ERROR = 'GET_DAY_ERROR';

export const UPDATE_DAY_AVAILABILITY_TRUE = 'UPDATE_DAY_AVAILABILITY_TRUE';
export const UPDATE_DAY_AVAILABILITY_TRUE_ERROR =
  'UPDATE_DAY_AVAILABILITY_TRUE_ERROR';
export const UPDATE_DAY_AVAILABILITY_FALSE = 'UPDATE_DAY_AVAILABILITY_FALSE';
export const UPDATE_DAY_AVAILABILITY_FALSE_ERROR =
  'UPDATE_DAY_AVAILABILITY_FALSE_ERROR';
export const DAYS_LOADING = 'DAYS_LOADING';
