FROM node:alpine

WORKDIR /workspace/

COPY package.json .

RUN yarn

COPY . .

ARG MONGO_USER=${MONGO_USER}
ARG MONGO_PASSWORD=${MONGO_PASSWORD}
ARG MONGO_DATABASE=${MONGO_DATABASE}

CMD ["yarn", "start:dev"]